export const SET_LOAN_INFO = "SET_LOAN_INFO";
export const SET_DESIRED_SPENDING = "SET_DESIRED_SPENDING";
export const ADD_LOAN = "ADD_LOAN";
export const UPDATE_LOAN = "UPDATE_LOAN";
export const SET_AVAILABLE_LOAN_PAYMENT_AMOUNT =
  "SET_AVAILABLE_LOAN_PAYMENT_AMOUNT";
export const SET_DESIRED_SPENDING_DATE = "SET_DESIRED_SPENDING_DATE";
