export const ADD_LOAN = "ADD_LOAN";
export const UPDATE_LOAN = "UPDATE_LOAN";
export const SET_AVAILABLE_LOAN_PAYMENT_AMOUNT =
  "SET_AVAILABLE_LOAN_PAYMENT_AMOUNT";
export const ADD_EXTRA_PAYMENT = "ADD_EXTRA_PAYMENT";
export const SET_DESIRED_SPENDING = "SET_DESIRED_SPENDING";
export const ADD_EXTRA_SPENDING = "ADD_EXTRA_SPENDING";
export const REMOVE_LOAN = "REMOVE_LOAN";
